// Code generated by qtc from "contents.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/contents.html:1
package views

//line views/contents.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/contents.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/contents.html:1
func StreamCommonContents(qw422016 *qt422016.Writer, section Section) {
//line views/contents.html:1
	qw422016.N().S(`

<!-- Section Title -->
<h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl">
    `)
//line views/contents.html:5
	qw422016.E().S(section.Title)
//line views/contents.html:5
	qw422016.N().S(`</h1>

`)
//line views/contents.html:7
	for _, content := range section.Contents {
//line views/contents.html:7
		qw422016.N().S(`

<br>

`)
//line views/contents.html:11
		if content.Subtitle != "" {
//line views/contents.html:11
			qw422016.N().S(`
<h2 class="text-4xl font-extrabold">`)
//line views/contents.html:12
			qw422016.E().S(content.Subtitle)
//line views/contents.html:12
			qw422016.N().S(`</h2>
<br>
`)
//line views/contents.html:14
		}
//line views/contents.html:14
		qw422016.N().S(`

`)
//line views/contents.html:16
		if len(content.TextList) != 0 {
//line views/contents.html:16
			qw422016.N().S(`
<div>`)
//line views/contents.html:17
			StreamText(qw422016, content.TextList)
//line views/contents.html:17
			qw422016.N().S(`</div>
<br>
`)
//line views/contents.html:19
		}
//line views/contents.html:19
		qw422016.N().S(`

`)
//line views/contents.html:21
		if content.Img != "" {
//line views/contents.html:21
			qw422016.N().S(`
<div>This is an Image `)
//line views/contents.html:22
			qw422016.E().S(content.Img)
//line views/contents.html:22
			qw422016.N().S(`</div>
<br>
`)
//line views/contents.html:24
		}
//line views/contents.html:24
		qw422016.N().S(`

`)
//line views/contents.html:26
		if content.RawHtml != "" {
//line views/contents.html:26
			qw422016.N().S(`
`)
//line views/contents.html:27
			qw422016.N().S(content.RawHtml)
//line views/contents.html:27
			qw422016.N().S(`
<br>
`)
//line views/contents.html:29
		}
//line views/contents.html:29
		qw422016.N().S(`

`)
//line views/contents.html:31
	}
//line views/contents.html:31
	qw422016.N().S(`
`)
//line views/contents.html:32
}

//line views/contents.html:32
func WriteCommonContents(qq422016 qtio422016.Writer, section Section) {
//line views/contents.html:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/contents.html:32
	StreamCommonContents(qw422016, section)
//line views/contents.html:32
	qt422016.ReleaseWriter(qw422016)
//line views/contents.html:32
}

//line views/contents.html:32
func CommonContents(section Section) string {
//line views/contents.html:32
	qb422016 := qt422016.AcquireByteBuffer()
//line views/contents.html:32
	WriteCommonContents(qb422016, section)
//line views/contents.html:32
	qs422016 := string(qb422016.B)
//line views/contents.html:32
	qt422016.ReleaseByteBuffer(qb422016)
//line views/contents.html:32
	return qs422016
//line views/contents.html:32
}
