// Code generated by qtc from "harold.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/harold.html:1
package views

//line views/harold.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/harold.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/harold.html:1
func StreamWebsiteHarold(qw422016 *qt422016.Writer) {
//line views/harold.html:1
	qw422016.N().S(`
<div x-data="{harold:false}">
    <button class="btn btn-primary" x-show="!harold" x-on:click="harold=true">
        Me Right Now
    </button>
    <img x-show="harold" src="./assets/website/harold.jpg" alt="./assets/website/harold.jpg" class="mx-auto h-full">
</div>
`)
//line views/harold.html:8
}

//line views/harold.html:8
func WriteWebsiteHarold(qq422016 qtio422016.Writer) {
//line views/harold.html:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/harold.html:8
	StreamWebsiteHarold(qw422016)
//line views/harold.html:8
	qt422016.ReleaseWriter(qw422016)
//line views/harold.html:8
}

//line views/harold.html:8
func WebsiteHarold() string {
//line views/harold.html:8
	qb422016 := qt422016.AcquireByteBuffer()
//line views/harold.html:8
	WriteWebsiteHarold(qb422016)
//line views/harold.html:8
	qs422016 := string(qb422016.B)
//line views/harold.html:8
	qt422016.ReleaseByteBuffer(qb422016)
//line views/harold.html:8
	return qs422016
//line views/harold.html:8
}
