// Code generated by qtc from "index.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/index.html:1
package views

//line views/index.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/index.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/index.html:1
func StreamIndex(qw422016 *qt422016.Writer, projectMap map[string]Project, sortApis []string) {
//line views/index.html:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset="utf-8">
    <meta name="description" content="Gianni Jiang">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="cyan">
    <title>Gianni Jiang</title>
    <link rel="stylesheet" href="./assets/tailwind.css">
    <script type="text/javascript" src="./assets/htmx.js"></script>
    <script async type="text/javascript" src="./assets/alpine.js"></script>
    <script type="text/javascript" src="./assets/classtools.js"></script>
    <link rel="manifest" href="./assets/manifest.json" />
    <link rel="icon" type="image/x-icon" href="./assets/favicon/favicon.ico">

    <!-- Debug -->
    <script>htmx.logAll()</script>

</head>

<body>

    <div class="flex overflow-auto" x-data="{activeProject:'website', activeSection:'introduction'}">
        <div id="side-menu" class="bg-teal-300 pt-[30px] w-1/6">
            `)
//line views/index.html:27
	StreamCommonSideMenu(qw422016, projectMap, sortApis)
//line views/index.html:27
	qw422016.N().S(`
        </div>

        <div id="contents" class="h-screen w-5/6 text-center pt-[30px] overflow-auto">
            `)
//line views/index.html:31
	StreamCommonContents(qw422016, projectMap["website"].SectionMap["introduction"])
//line views/index.html:31
	qw422016.N().S(`
        </div>
    </div>




</body>

</html>
`)
//line views/index.html:41
}

//line views/index.html:41
func WriteIndex(qq422016 qtio422016.Writer, projectMap map[string]Project, sortApis []string) {
//line views/index.html:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.html:41
	StreamIndex(qw422016, projectMap, sortApis)
//line views/index.html:41
	qt422016.ReleaseWriter(qw422016)
//line views/index.html:41
}

//line views/index.html:41
func Index(projectMap map[string]Project, sortApis []string) string {
//line views/index.html:41
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.html:41
	WriteIndex(qb422016, projectMap, sortApis)
//line views/index.html:41
	qs422016 := string(qb422016.B)
//line views/index.html:41
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.html:41
	return qs422016
//line views/index.html:41
}
