// Code generated by qtc from "numbersApi.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/numbersApi.html:1
package views

//line views/numbersApi.html:1
import "strconv"

//line views/numbersApi.html:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/numbersApi.html:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/numbersApi.html:2
func StreamNumbersApi(qw422016 *qt422016.Writer) {
//line views/numbersApi.html:2
	qw422016.N().S(`
<div class="flex justify-center gap-20 p-4">
    <button hx-get="number" hx-target="#numbers-api" class="btn btn-accent">
        Random
    </button>
</div>

<div id="numbers-api" class="transition"></div>
`)
//line views/numbersApi.html:10
}

//line views/numbersApi.html:10
func WriteNumbersApi(qq422016 qtio422016.Writer) {
//line views/numbersApi.html:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/numbersApi.html:10
	StreamNumbersApi(qw422016)
//line views/numbersApi.html:10
	qt422016.ReleaseWriter(qw422016)
//line views/numbersApi.html:10
}

//line views/numbersApi.html:10
func NumbersApi() string {
//line views/numbersApi.html:10
	qb422016 := qt422016.AcquireByteBuffer()
//line views/numbersApi.html:10
	WriteNumbersApi(qb422016)
//line views/numbersApi.html:10
	qs422016 := string(qb422016.B)
//line views/numbersApi.html:10
	qt422016.ReleaseByteBuffer(qb422016)
//line views/numbersApi.html:10
	return qs422016
//line views/numbersApi.html:10
}

//line views/numbersApi.html:12
func StreamNumbersApiResponse(qw422016 *qt422016.Writer, n int, contents string) {
//line views/numbersApi.html:12
	qw422016.N().S(`
<div id="numbers-api" class="flex justify-center gap-20">

    <div class="card w-96" x-data="{number:`)
//line views/numbersApi.html:15
	qw422016.E().S(strconv.Itoa(n))
//line views/numbersApi.html:15
	qw422016.N().S(`}"
        :class="{'bg-green-200':number % 2 === 0, 'bg-orange-200':number % 2 !== 0}">
        <div class="card-body">
            <h2 class="card-title">Number `)
//line views/numbersApi.html:18
	qw422016.E().S(strconv.Itoa(n))
//line views/numbersApi.html:18
	qw422016.N().S(`</h2>
            <p>`)
//line views/numbersApi.html:19
	qw422016.E().S(contents)
//line views/numbersApi.html:19
	qw422016.N().S(`</p>
        </div>
    </div>

</div>
`)
//line views/numbersApi.html:24
}

//line views/numbersApi.html:24
func WriteNumbersApiResponse(qq422016 qtio422016.Writer, n int, contents string) {
//line views/numbersApi.html:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/numbersApi.html:24
	StreamNumbersApiResponse(qw422016, n, contents)
//line views/numbersApi.html:24
	qt422016.ReleaseWriter(qw422016)
//line views/numbersApi.html:24
}

//line views/numbersApi.html:24
func NumbersApiResponse(n int, contents string) string {
//line views/numbersApi.html:24
	qb422016 := qt422016.AcquireByteBuffer()
//line views/numbersApi.html:24
	WriteNumbersApiResponse(qb422016, n, contents)
//line views/numbersApi.html:24
	qs422016 := string(qb422016.B)
//line views/numbersApi.html:24
	qt422016.ReleaseByteBuffer(qb422016)
//line views/numbersApi.html:24
	return qs422016
//line views/numbersApi.html:24
}
