// Code generated by qtc from "sidemenu.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/sidemenu.html:1
package views

//line views/sidemenu.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/sidemenu.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/sidemenu.html:1
func StreamCommonSideMenu(qw422016 *qt422016.Writer, projectMap map[string]Project, sortApis []string, currentProject string, currentSection string) {
//line views/sidemenu.html:2
	qw422016.N().S(`

<!-- <a href="#" aria-current="page" class="inline-block p-4 text-blue-600 bg-gray-100 rounded-t-lg active dark:bg-gray-800 dark:text-blue-500">Profile</a>

<a href="#" class="inline-block p-4 rounded-t-lg hover:text-gray-600 hover:bg-gray-50 dark:hover:bg-gray-800 dark:hover:text-gray-300">Dashboard</a> -->

<div>

    `)
//line views/sidemenu.html:10
	for _, projectApi := range sortApis {
//line views/sidemenu.html:10
		qw422016.N().S(`

    `)
//line views/sidemenu.html:12
		isCurrentProject := currentProject == projectApi

//line views/sidemenu.html:12
		qw422016.N().S(`
    `)
//line views/sidemenu.html:13
		project := projectMap[projectApi]

//line views/sidemenu.html:13
		qw422016.N().S(`

    <div class="project `)
//line views/sidemenu.html:15
		if isCurrentProject {
//line views/sidemenu.html:15
			qw422016.N().S(`bg-blue-200`)
//line views/sidemenu.html:15
		}
//line views/sidemenu.html:15
		qw422016.N().S(`">
        <a hx-get="`)
//line views/sidemenu.html:16
		qw422016.E().V(project.Api)
//line views/sidemenu.html:16
		qw422016.N().S(`" hx-target="#contents"
            class="no-underline text-[25px] text-cyan-700 hover:text-cyan-900 block transition-[0.3s] pl-8 pr-2 py-2">`)
//line views/sidemenu.html:18
		qw422016.E().S(project.Title)
//line views/sidemenu.html:18
		qw422016.N().S(`</a>
    </div>


    `)
//line views/sidemenu.html:22
		if isCurrentProject {
//line views/sidemenu.html:22
			qw422016.N().S(`
    `)
//line views/sidemenu.html:23
			for _, sectionApi := range project.SortApis {
//line views/sidemenu.html:23
				qw422016.N().S(`

    `)
//line views/sidemenu.html:25
				isCurrentSection := currentSection == sectionApi

//line views/sidemenu.html:25
				qw422016.N().S(`
    `)
//line views/sidemenu.html:26
				section := project.SectionMap[sectionApi]

//line views/sidemenu.html:26
				qw422016.N().S(`

    <div class="section `)
//line views/sidemenu.html:28
				if isCurrentSection {
//line views/sidemenu.html:28
					qw422016.N().S(`bg-blue-100`)
//line views/sidemenu.html:28
				}
//line views/sidemenu.html:28
				qw422016.N().S(`">
        <a hx-get="`)
//line views/sidemenu.html:29
				qw422016.E().V(projectApi)
//line views/sidemenu.html:29
				qw422016.N().S(`/`)
//line views/sidemenu.html:29
				qw422016.E().V(sectionApi)
//line views/sidemenu.html:29
				qw422016.N().S(`" hx-target="#contents"
            class="no-underline text-[20px] text-cyan-700 hover:text-cyan-900 block transition-[0.3s] pl-12 pr-2 py-2">`)
//line views/sidemenu.html:31
				qw422016.E().S(section.Title)
//line views/sidemenu.html:31
				qw422016.N().S(`</a>
    </div>
    `)
//line views/sidemenu.html:33
			}
//line views/sidemenu.html:33
			qw422016.N().S(`
    `)
//line views/sidemenu.html:34
		}
//line views/sidemenu.html:34
		qw422016.N().S(`

    `)
//line views/sidemenu.html:36
	}
//line views/sidemenu.html:36
	qw422016.N().S(`

</div>

`)
//line views/sidemenu.html:40
}

//line views/sidemenu.html:40
func WriteCommonSideMenu(qq422016 qtio422016.Writer, projectMap map[string]Project, sortApis []string, currentProject string, currentSection string) {
//line views/sidemenu.html:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/sidemenu.html:40
	StreamCommonSideMenu(qw422016, projectMap, sortApis, currentProject, currentSection)
//line views/sidemenu.html:40
	qt422016.ReleaseWriter(qw422016)
//line views/sidemenu.html:40
}

//line views/sidemenu.html:40
func CommonSideMenu(projectMap map[string]Project, sortApis []string, currentProject string, currentSection string) string {
//line views/sidemenu.html:40
	qb422016 := qt422016.AcquireByteBuffer()
//line views/sidemenu.html:40
	WriteCommonSideMenu(qb422016, projectMap, sortApis, currentProject, currentSection)
//line views/sidemenu.html:40
	qs422016 := string(qb422016.B)
//line views/sidemenu.html:40
	qt422016.ReleaseByteBuffer(qb422016)
//line views/sidemenu.html:40
	return qs422016
//line views/sidemenu.html:40
}
