// Code generated by qtc from "tailwind.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/tailwind.html:1
package views

//line views/tailwind.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/tailwind.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/tailwind.html:1
func StreamTailwindDemo(qw422016 *qt422016.Writer) {
//line views/tailwind.html:1
	qw422016.N().S(`
<div class="animate-bounce bg-orange-200 font-bold border-8 border-teal-400 text-red-700 hover:bg-purple-200">
    Hello
    World</div>
`)
//line views/tailwind.html:5
}

//line views/tailwind.html:5
func WriteTailwindDemo(qq422016 qtio422016.Writer) {
//line views/tailwind.html:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/tailwind.html:5
	StreamTailwindDemo(qw422016)
//line views/tailwind.html:5
	qt422016.ReleaseWriter(qw422016)
//line views/tailwind.html:5
}

//line views/tailwind.html:5
func TailwindDemo() string {
//line views/tailwind.html:5
	qb422016 := qt422016.AcquireByteBuffer()
//line views/tailwind.html:5
	WriteTailwindDemo(qb422016)
//line views/tailwind.html:5
	qs422016 := string(qb422016.B)
//line views/tailwind.html:5
	qt422016.ReleaseByteBuffer(qb422016)
//line views/tailwind.html:5
	return qs422016
//line views/tailwind.html:5
}
