// Code generated by qtc from "todoMain.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/todoMain.html:1
package views

//line views/todoMain.html:1
import "github.com/Jiang-Gianni/gianni-jiang/db"

//line views/todoMain.html:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/todoMain.html:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/todoMain.html:2
func StreamTodoMain(qw422016 *qt422016.Writer, todos []db.GetAllTodoRow) {
//line views/todoMain.html:2
	qw422016.N().S(`
<h1
    class="mb-5 text-3xl font-bold leading-tight text-teal-500 dark:text-teal-500 sm:text-4xl sm:leading-tight md:text-5xl md:leading-tight text-center">
    Todo App</h1>
`)
//line views/todoMain.html:6
	StreamTodoTable(qw422016, todos)
//line views/todoMain.html:6
	qw422016.N().S(`
`)
//line views/todoMain.html:7
}

//line views/todoMain.html:7
func WriteTodoMain(qq422016 qtio422016.Writer, todos []db.GetAllTodoRow) {
//line views/todoMain.html:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/todoMain.html:7
	StreamTodoMain(qw422016, todos)
//line views/todoMain.html:7
	qt422016.ReleaseWriter(qw422016)
//line views/todoMain.html:7
}

//line views/todoMain.html:7
func TodoMain(todos []db.GetAllTodoRow) string {
//line views/todoMain.html:7
	qb422016 := qt422016.AcquireByteBuffer()
//line views/todoMain.html:7
	WriteTodoMain(qb422016, todos)
//line views/todoMain.html:7
	qs422016 := string(qb422016.B)
//line views/todoMain.html:7
	qt422016.ReleaseByteBuffer(qb422016)
//line views/todoMain.html:7
	return qs422016
//line views/todoMain.html:7
}
